### ISSUE TITLE
re: WaniKani Stats

### ISSUE THREAD

**Issue by kayleighthorpe** [matryer/bitbar-plugins#1306]
FAO: (@Nzebo)

Hi there! Having trouble with the WaniKani stats bar, here's the error it gives when using:

Current Level Progress | size=12 color=#BFBFBF
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/time.rb:254:in `make_time': no time information in "" (ArgumentError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/time.rb:366:in `parse'
	from /Users/kay/Documents/bitbar/waniKaniStats.5m.rb:239:in `calc_level_percentage'
	from /Users/kay/Documents/bitbar/waniKaniStats.5m.rb:328:in `print_data'
	from /Users/kay/Documents/bitbar/waniKaniStats.5m.rb:371:in `<main>'

Any advice?

Thanks!

**Comment by sprak3000** [comment]
Closing due to age and lack of plugin author response.
