### ISSUE TITLE
Weather/OpenWeatherMap/weather.15m.py  UnicodeEncodeError

### ISSUE THREAD

**Issue by sebastienroux** [matryer/bitbar-plugins#206]
Hello,

This plugin isn't working properly sometimes, because of encoding issue : 

`Traceback (most recent call last):
  File "/Users/sebastien/Documents/BitBarPlugins/Enabled/weather.15m.py", line 61, in <module>
    print render_wx()
  File "/Users/sebastien/Documents/BitBarPlugins/Enabled/weather.15m.py", line 54, in render_wx
    weather_data = get_wx()
  File "/Users/sebastien/Documents/BitBarPlugins/Enabled/weather.15m.py", line 44, in get_wx
    'condition': str(wx['weather'][0]['description']),
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)`

My settings : 

```
location = '2988507'
units = 'metric' # kelvin, metric, imperial
lang = 'fr'
```

Thanks 

Se

**Comment by seripap** [comment]
#227 should fix this for you. Cheers

**Comment by keithamus** [comment]
@sebastienroux  - #227 has been merged. I'll close this for now - but let us know if you have any more problems and we can re-open it.
