### ISSUE TITLE
re: Yahoo Finance Stock Ticker

### ISSUE THREAD

**Issue by alfism** [matryer/bitbar-plugins#900]
FAO: (@bp1222)

This happening for anyone else?

❯❯❯ ./yahoo-stock.1m.py
Traceback (most recent call last):
  File "./yahoo-stock.1m.py", line 15, in <module>
    u = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 999: Request denied

**Comment by bp1222** [comment]
Yes, last night I noticed it.  Seems yahoo decided to pull this interface too.

**Comment by alfism** [comment]
Looks like it is being shut down for good:

Yahoo! - 403 Forbidden  -- error 403

It has come to our attention that this service is being used in violation of the Yahoo Terms of Service.  As such, the service is being discontinued.  For all future markets and equities data research, please refer to finance.yahoo.com.

**Comment by rkanter** [comment]
I created a replacement plugin that uses a different API (https://iextrading.com/developer).  The resulting output looks the same as the original Yahoo! plugin.

https://github.com/matryer/bitbar-plugins/pull/945

**Comment by tresni** [comment]
#937 was merged and gives a new stock ticket option.
